name: free_form_video_inpainting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.6=h470a237_2
  - cairo=1.14.12=h276e583_5
  - ffmpeg=4.0.2=ha0c5888_2
  - fontconfig=2.13.1=h65d0f4c_0
  - freeglut=3.0.0=hfc679d8_5
  - gettext=0.19.8.1=h5e8e0c9_1
  - glib=2.56.2=h464dc38_1
  - gmp=6.1.2=hfc679d8_0
  - gnutls=3.5.19=h2a4e5f8_1
  - graphite2=1.3.12=hfc679d8_1
  - harfbuzz=1.9.0=h04dbb29_1
  - hdf5=1.10.2=hc401514_2
  - icu=58.2=hfc679d8_0
  - imageio=2.4.1=py37_0
  - jpeg=9c=h470a237_1
  - libgfortran=3.0.0=1
  - libglu=9.0.0=hfc679d8_0
  - libiconv=1.15=h470a237_3
  - libxcb=1.13=h470a237_2
  - libxml2=2.9.8=h422b904_5
  - nettle=3.3=0
  - openh264=1.8.0=hd28b015_0
  - pillow=5.3.0=py37hc736899_0
  - pixman=0.34.0=h470a237_3
  - pthread-stubs=0.4=h470a237_1
  - setuptools=40.6.2=py37_0
  - six=1.11.0=py37_1
  - wheel=0.32.3=py37_0
  - x264=1!152.20180717=h470a237_1
  - xorg-kbproto=1.0.7=h470a237_2
  - xorg-libice=1.0.9=h470a237_4
  - xorg-libsm=1.2.3=h8c8a85c_0
  - xorg-libx11=1.6.6=h470a237_0
  - xorg-libxau=1.0.8=h470a237_6
  - xorg-libxdmcp=1.1.2=h470a237_7
  - xorg-libxext=1.3.3=h470a237_4
  - xorg-libxrender=0.9.10=h470a237_2
  - xorg-renderproto=0.11.1=h470a237_2
  - xorg-xextproto=7.3.0=h470a237_2
  - xorg-xproto=7.0.31=h470a237_7
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py37_0
  - cffi=1.11.5=py37he75722e_1
  - cloudpickle=0.6.1=py37_0
  - coloredlogs=10.0=py37_0
  - cycler=0.10.0=py37_0
  - dask-core=1.0.0=py37_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py37_0
  - expat=2.2.6=he6710b0_0
  - flake8=3.6.0=py37_0
  - freetype=2.9.1=h8a8886c_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - humanfriendly=4.17=py37_0
  - intel-openmp=2019.1=144
  - jasper=2.0.14=h07fcdf6_1
  - kiwisolver=1.0.1=py37hf484d3e_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libopencv=3.4.2=hb342d67_1
  - libpng=1.6.35=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - matplotlib=2.2.2=py37hb69df0a_2
  - mccabe=0.6.1=py37_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py37h7dd41cf_0
  - mkl_random=1.0.1=py37h4414c95_1
  - ncurses=6.1=he6710b0_1
  - networkx=2.2=py37_1
  - ninja=1.8.2=py37h6bb024c_1
  - numpy=1.15.4=py37h1d66e8a_0
  - numpy-base=1.15.4=py37h81de0dd_0
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1a=h7b6447c_0
  - pcre=8.42=h439df22_0
  - pip=18.1=py37_0
  - py-opencv=3.4.2=py37hb342d67_1
  - pycodestyle=2.4.0=py37_0
  - pycparser=2.19=py37_0
  - pyflakes=2.0.0=py37_0
  - pyparsing=2.3.0=py37_0
  - pyqt=5.6.0=py37h22d08a2_6
  - python=3.7.1=h0371630_3
  - python-dateutil=2.7.5=py37_0
  - pytz=2018.7=py37_0
  - pywavelets=1.0.1=py37hdd07704_0
  - qt=5.6.3=h8bf5577_3
  - readline=7.0=h7b6447c_5
  - scikit-image=0.14.0=py37hf484d3e_1
  - scipy=1.1.0=py37hfa4b5c9_1
  - sip=4.18.1=py37hf484d3e_2
  - sqlite=3.25.3=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py37_0
  - tornado=5.1.1=py37h7b6447c_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pytorch=1.0.0=py3.7_cuda9.0.176_cudnn7.4.1_1
  - torchvision=0.2.1=py37_1
  - pip:
    - dask==1.0.0
    - protobuf==3.6.1
    - tensorboardx==1.5
    - torch==1.0.0
    - dlib
